### ISSUE TITLE
Stops monitoring server after server restart

### ISSUE THREAD

**Issue by ibigpapa** [Team-Silver-Sphere/SquadJS#79] opened 2020-09-24 14:22 UTC
### Description of Issue
We daily morning restarts of the server (Best practice from squad hosting discord),  Every morning the app starts reporting an Unhandled Promise Rejection Warning and stops working.  We no longer squad admin pings, TK log stops, no longer issuing TK warnings.

### Errors or Screenshots of Issue
```(node:4748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1035)
(node:4748) UnhandledPromiseRejectionWarning: Error: Not connected.
    at file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:185:16
    at new Promise (<anonymous>)
    at Rcon.write (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:179:12)
    at Rcon.execute (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:54:17)
    at Rcon.getMapInfo (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:58:33)
    at Timeout._onTimeout (file:///C:/servers/squadjs-current/SquadJS/squad-server/index.js:53:36)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)```

### Squad Information
 * SquadJS Version: 1.4.1
 * Squad Version: 1.0.0.143.39036

### System Information
 * Operating System: Windows 10
 * NodeJS Version: v14.5.0
 * Yarn Version: 1.22.4

**Comment by Thomas-Smyth** [comment] 2020-09-24 14:37
Duplicate of https://github.com/Thomas-Smyth/SquadJS/issues/34

**Comment by ect0s** [comment] 2020-10-19 16:42
I may have solved this issue. 

The first thing I tried was backing off the rcon reconnect interval; this was semi successful, but in fact not the root cause. 

The issue lies in the reconnectInterval Try:Catch block. 

        'this.reconnectInterval = setInterval(async () => {
          this.verbose('Attempting AutoReconnect.');
          try {
            await this.connect();
            clearInterval(this.reconnectInterval);
            this.reconnectInterval = null;
            this.verbose('Cleaned AutoReconnect.');
          } catch (err) {
            this.verbose('AutoReconnect Failed.');
          }'

What in fact was happening, looking at the logged output, is that we never saw 'AutoReconnect Failed' OR 'AutoReconnect Cleaned' 

'[1602598554923] RCON (Verbose): Attempting AutoReconnect.
[1602598554923] RCON (Verbose): Method Exec: connect()
[1602598554923] RCON (Verbose): Socket Opened.
[1602598554923] RCON (Verbose): Sending auth packet...
[1602598554927] RCON (Verbose): Socket Closed. AutoReconnect: true'

This is because when we enter the ReconnectInterval, and call this.connect(), it starts stacking rcon connections to the squad server, even though it has already connected once. The squad server doesn't show rcon connections opening, only closing, and it will forcably close connections when a host starts another one or exceeds the connection limit. 

Now, Im not a javascript coder, but I did look a how variable scopes work within try{}/catch{} and how they get hoisted. 

Our fix, which let me bring the reconnect interval down to 100ms was to simply rearrange the code within the try{} block:

          'try {
            clearInterval(this.reconnectInterval);
            this.reconnectInterval = null;
            await this.connect();
            this.verbose('Cleaned AutoReconnect.');
          }'

I think this might be related to calling this.connect when during its call, the reconnectInterval is not nulled, and we haven't cleared the interval to stop (re)execution. 

That re-execution never rejects or resolves the new this.connect() promise, because it starts up the reconnectInterval() again, which continues to run.

By default, this then fires off another reconnection attempt, and the squad server force closes a connection, stacking the issue further. 

I might be wrong about the specifics, but for a fact, the try{} block was never catching or resolving with reconnect cleaned, and the squad server was seeing multiple rcon connections, and forcably closing them. 

As an aside, since this is already here:

The rejected promises that trigger outside of this loop are related to rcon connections failing or not being up, while they are set on an Interval timer that isn't enabled or disabled when rcon is down. ListPlayers, MapInfo and so on. GameDig is another one that also fails. I added error handling to a few of these and was rid of all the extra rejected promise warnings. They were not directly related to the rcon issue.

**Comment by bumbummen99** [comment] 2020-10-19 17:26
I did not take a big look into this but setInterval is not async so it is possible that the code can be run multiple times at the same time. The interval would have to properly cancel the previous context, tought this could be possibly refactored to get rid of setInterval.

**Comment by ect0s** [comment] 2020-10-19 17:31
This gets into Var hoisting and scope, which Im a noob at. 

Basically, I think that 'await connect()' ends up blocking the variables getting reassigned, because the rest of the try block was never executing, including the catch. 

Sequentially setting up state before running connect appeared to fix it on my end, but this is beyond my expertise. 

I did some  googling about try{} and catch, and basically, if the try: fails or does not finish, vars under it never take the new state. 

In this case, we just kept falling into the loop over and over again

connect calls connect again, because we never cleared the interval.

**Comment by Thomas-Smyth** [comment] 2020-10-19 17:37
> This is because when we enter the ReconnectInterval, and call this.connect(), it starts stacking rcon connections to the squad server, even though it has already connected once.

Once `this.connect()` succeeds it should clear the interval so there should be no point when a socket is opened and the reconnection interval is firing? If this is the case we should find out why. 

I presume as this issue appears to be related only to server restarts when the server is down the first response takes longer to timeout than the interval firing a new `this.connect()` call resulting in two sockets. Though, that would depend on whether the `close` event is fired even though the socket variable is overwritten on the second call.

Regardless, I don't think a more significant rewrite is required than your proposal. If the `close` event is fired in all instances of us failing to connect to the server then we simply need a timeout in the close event so it is only fired once rather than the interval that can be fired multiple times, possibly including when a connection attempt is still running.

**Comment by ect0s** [comment] 2020-10-19 17:40
I'll defer to you Tommy, Noob here. 

Just stating what I saw, multiple connections happened and we never saw 'Interval Cleaned' or 'Auto Reconnect Failed'; 

Moving the variables up suddenly made both those log lines show up as needed. 

And the squad server, on startup, can take a short bit to respond on rcon, meaning you end up in something of a race condition where things might break. At least, thats what I thought at first. 

How I figured this out, was adding a log line to the connect() promise resolving and rejecting, and saw it resolve multiple times in a row without logging the 'interval' cleared'

**Comment by Thomas-Smyth** [comment] 2020-10-19 17:44
> Just stating what I saw, multiple connections happened and we never saw 'Interval Cleaned' or 'Auto Reconnect Failed';

Good spot.

For future reference, logs from https://github.com/Thomas-Smyth/SquadJS/issues/34:
```
[1595052031199] RCON (Verbose): Socket Error: connect ECONNREFUSED x.x.x.x:21114
[1595052031199] RCON (Verbose): Error Opening Socket: connect ECONNREFUSED x.x.x.x:21114
[1595052031199] RCON (Verbose): AutoReconnect Failed.
[1595052031199] RCON (Verbose): Socket Closed. AutoReconnect: true
[1595052036201] RCON (Verbose): Attempting AutoReconnect.
[1595052036201] RCON (Verbose): Method Exec: connect()
[1595052036201] RCON (Verbose): Socket Opened.
[1595052036201] RCON (Verbose): Sending auth packet...
[1595052041202] RCON (Verbose): Attempting AutoReconnect.
[1595052041202] RCON (Verbose): Method Exec: connect()
[1595052041202] RCON (Verbose): Socket Opened.
[1595052041202] RCON (Verbose): Sending auth packet...
[1595052041207] RCON (Verbose): Socket Closed. AutoReconnect: true
```

The timeout is definitely the way forwards I think... even if it doesn't solve the issue it will be an improvement.

Will probably look to address this in v2.

**Comment by ect0s** [comment] 2020-10-19 17:56
Sorry to bump this again. 

Connect wasn't clearing the interval because that await this.connect needs a promise to resolve, but it was falling into the interval again, which spawned a new promise that needs to resolve and so on. 

Had to relook at things, but I don't think this is in relation to the close(); except that those close(); statements in the log are the squad server rejecting new connections

**Comment by Thomas-Smyth** [comment] 2020-10-19 19:42
> Had to relook at things, but I don't think this is in relation to the close(); except that those close(); statements in the log are the squad server rejecting new connections

I meant the `close` event on the socket in SquadJS's RCON.

**Comment by ect0s** [comment] 2020-10-21 14:26
Did a bit more digging today. I think I might be able to phrase this appropriately below. 

Within the setInterval and the try catch block, the 'this. ...' assignments are running within a new context. Setting them first means that they do work within this new context, and not the old/orig context. 

connect( setInterval( connect( setInterval() ) ) and so on. Over progressive successful reconnects we still stack context/loop.  

This fixes things temporarily, but I've seen a slow memory growth over the last few days that might be symptomatic of the above.

Wouldn't it be easier to have close() emit an event that starts the new instance, so we call connect() from the global context above it?

I might be an idiot here, so feel free to chime in.

**Comment by Thomas-Smyth** [comment] 2020-10-22 19:47
> Wouldn't it be easier to have close() emit an event that starts the new instance, so we call connect() from the global context above it?

It should still ideally be self-contained.

I just looked at it now prior to properly reading your last message and I stumbled upon the same problem of how to do it without a massive callback stack. This might be a little harder than I originally thought.

**Comment by Thomas-Smyth** [comment] 2020-10-22 22:37
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals

This article does not warn against recursive timeouts from what I read.

https://medium.com/@devinmpierce/recursive-settimeout-8eb953b02b98

This does however.

**Comment by bumbummen99** [comment] 2020-10-23 11:33
You also have to consider that it is async too, that means it will keep running even if you clear the timeout so you would have to cancel the promise somehow.

**Comment by Thomas-Smyth** [comment] 2020-10-23 11:42
Had a play last night as I was concerned that some other timeouts were affected by this.

In v2 we use recursive timeouts, e.g. https://github.com/Thomas-Smyth/SquadJS/blob/v2/squad-server/index.js#L252, however, the issue is not present as far as I can tell from callstacks. I believe it's because the context is bound to `this` in the constructor.

Another idea is to use a `while` loop that will await a promise that resolved when the socket closes and then reboots it when it does, providing it wasn't an intentional closure.

**Closed as completed** 2021-03-05 17:12 UTC
Labels: core bug
