### ISSUE TITLE
RCON Connection problem || UNIX

### ISSUE THREAD

**Issue by SiDronee** [Team-Silver-Sphere/SquadJS#34] opened 2020-07-14 16:00 UTC
### Squad Information
 * SquadJS Version: V1.1.0
 * Squad Version: Current

### System Information
 * Operating System: Ubuntu 19.10
 * NodeJS Version: v14.4.0
 * Yarn Version: 1.22.4

### Description of Issue
Still getting RCON problems resulting in not updating the Teamkill logs >  MySQL & influnc DB
Temp FIX is restarting the bot every 1 hour to be sure..

error: `
(node:15153) UnhandledPromiseRejectionWarning: Error: Not connected.
14|SquadJS #1  |     at file:///home/XXXXX/SquadJS/squad-server/rcon/index.js:185:16
14|SquadJS #1  |     at new Promise (<anonymous>)
14|SquadJS #1  |     at Rcon.write (file:///home/XXXXX/SquadJS/squad-server/rcon/index.js:179:12)
14|SquadJS #1  |     at Rcon.execute (file:///home/XXXXX/SquadJS/squad-server/rcon/index.js:54:17)
14|SquadJS #1  |     at Rcon.getMapInfo (file:///home/XXXXX/SquadJS/squad-server/rcon/index.js:58:33)
14|SquadJS #1  |     at Timeout._onTimeout (file:///home/XXXXX/SquadJS/squad-server/index.js:56:36)
14|SquadJS #1  |     at listOnTimeout (internal/timers.js:549:17)
14|SquadJS #1  |     at processTimers (internal/timers.js:492:7)
14|SquadJS #1  | (node:15153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4921)
`

Second error, current SquadJS version: 
`(node:15153) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN host
14|SquadJS #1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
14|SquadJS #1  | (node:15153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4929)
`

**Comment by bumbummen99** [comment] 2020-07-14 16:16
The `execute` methoid in rcon/index.js returns a Promise that **can** throw errors / reject with an error.
https://github.com/Thomas-Smyth/SquadJS/blob/2b93d0da2c8f78e12aebb3df6abf3a1e8ad3217a/squad-server/rcon/index.js#L54
https://github.com/Thomas-Smyth/SquadJS/blob/2b93d0da2c8f78e12aebb3df6abf3a1e8ad3217a/squad-server/rcon/index.js#L180
Therefore calls to execute should handle rejected Promises.

**Comment by Thomas-Smyth** [comment] 2020-07-14 18:22
> The `execute` methoid in rcon/index.js returns a Promise that **can** throw errors / reject with an error.
> https://github.com/Thomas-Smyth/SquadJS/blob/2b93d0da2c8f78e12aebb3df6abf3a1e8ad3217a/squad-server/rcon/index.js#L54
> 
> 
> https://github.com/Thomas-Smyth/SquadJS/blob/2b93d0da2c8f78e12aebb3df6abf3a1e8ad3217a/squad-server/rcon/index.js#L180
> 
> 
> Therefore calls to execute should handle rejected Promises.

Unfortunately, this is not the root cause of the problem. Whilst error handling is probably something I should improve, it would be good to be able to resolve the cause of these errors.

I know you have supplied it to me on Discord in the past, but are you able to supply some more examples of the RCON verbose logging along with the errors in chronological orders? Furthermore, for some of the errors you have sent me in the past, you were not able to tell me whether it recovered after the error. It would be helpful to have at least one set of logs where it definitely did not recover in order to be able to narrow down the issue.

Based on the logs you have sent me in the past I suspect that RCON commands running between a disconnect and the auto-reconnect reconnecting you somehow breaks the auto-reconnection. As far as I'm aware you are the only one experiencing the issues and I am fairly sure it has not broken for me in the circumstances I describe so it would be really good to get a set of logs to work from.

**Comment by Thomas-Smyth** [comment] 2020-07-19 21:22
Logs from @SiDronee:
```
[1595052031199] RCON (Verbose): Socket Error: connect ECONNREFUSED x.x.x.x:21114
[1595052031199] RCON (Verbose): Error Opening Socket: connect ECONNREFUSED x.x.x.x:21114
[1595052031199] RCON (Verbose): AutoReconnect Failed.
[1595052031199] RCON (Verbose): Socket Closed. AutoReconnect: true
[1595052036201] RCON (Verbose): Attempting AutoReconnect.
[1595052036201] RCON (Verbose): Method Exec: connect()
[1595052036201] RCON (Verbose): Socket Opened.
[1595052036201] RCON (Verbose): Sending auth packet...
[1595052041202] RCON (Verbose): Attempting AutoReconnect.
[1595052041202] RCON (Verbose): Method Exec: connect()
[1595052041202] RCON (Verbose): Socket Opened.
[1595052041202] RCON (Verbose): Sending auth packet...
[1595052041207] RCON (Verbose): Socket Closed. AutoReconnect: true
```
The connection had been for a while for whatever reason (Edit: According to PM2 logs it looks like the Squad server closed and was started again). It then began connecting successfully again but was not able to authenticate and got stuck in a loop of connecting, sending an auth packet, and then disconnecting.

Hopefully, this is enough to begin to try and replicate the issue.

**Comment by ibigpapa** [comment] 2020-09-20 14:11
I think this error is similar to the one i'm experiencing on windows

```(node:10908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 768)
(node:10908) UnhandledPromiseRejectionWarning: Error: Not connected.
    at file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:185:16
    at new Promise (<anonymous>)
    at Rcon.write (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:179:12)
    at Rcon.execute (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:54:17)
    at Rcon.getMapInfo (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:58:33)
    at Timeout._onTimeout (file:///C:/servers/squadjs-current/SquadJS/squad-server/index.js:53:36)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)```

We restart the server daily.  Every restart squadjs can't recover and has to be restarted to start to work.

running lastest 1.4.1

**Comment by ibigpapa** [comment] 2020-10-09 12:59
Anything I can do to help resolve this one?  Restarting the bot daily is becoming a chore.

**Comment by wiilover22** [comment] 2020-10-11 00:03
We're having the same issue. If the squad server is either restarted manually, or crashes - SquadJS loses the RCON connection and gets stuck in the AutoReconnect loop which looks like this in the console:

[1602373324931] RCON (Verbose): Socket Closed. AutoReconnect: true
[1602373329932] RCON (Verbose): Attempting AutoReconnect.
[1602373329932] RCON (Verbose): Method Exec: connect()
[1602373329933] RCON (Verbose): Socket Error: connect ECONNREFUSED 192.168.1.30:21114
[1602373329933] RCON (Verbose): Error Opening Socket: connect ECONNREFUSED 192.168.1.30:21114
[1602373329933] RCON (Verbose): AutoReconnect Failed.
[1602373329933] RCON (Verbose): Socket Closed. AutoReconnect: true
[1602373334935] RCON (Verbose): Attempting AutoReconnect.
[1602373334935] RCON (Verbose): Method Exec: connect()
[1602373334936] RCON (Verbose): Socket Opened.
[1602373334936] RCON (Verbose): Sending auth packet...
[1602373339936] RCON (Verbose): Attempting AutoReconnect.

Only solution appears to be killing, and restarting SquadJS.

**Comment by ibigpapa** [comment] 2020-10-13 14:40
So I set `unhandled-rejections=strict`  and got this log

```
PS C:\servers\squadjs-current\SquadJS> node --unhandled-rejections=strict .\index.js

   _____  ____  _    _         _____   _
  / ____|/ __ \| |  | |  /\   |  __ \ (_)
 | (___ | |  | | |  | | /  \  | |  | | _ ___
  \___ \| |  | | |  | |/ /\ \ | |  | || / __|
  ____) | |__| | |__| / ____ \| |__| || \__ \
 |_____/ \___\_\\____/_/    \_\_____(_) |___/
                                     _/ |
                                    |__/
TEAMDIXX, Copyright 2020
GitHub: https://github.com/Thomas-Smyth/SquadJS
Version: 1.4.1

SquadJS factory commencing building...
Getting config file...
Building Squad server...
Initialising connectors...
Starting discordClient connector...
Loading plugins...
Loading plugin auto-tk-warn...
Loading plugin discord-admin-request...
Loading plugin discord-teamkill...
Watching server 1...
file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:181
        reject(new Error('Unable to write to socket'));
               ^

Error: Unable to write to socket
    at file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:181:16
    at new Promise (<anonymous>)
    at Rcon.write (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:179:12)
    at Rcon.execute (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:54:17)
    at Rcon.listPlayers (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:67:33)
    at Server.updatePlayers (file:///C:/servers/squadjs-current/SquadJS/squad-server/index.js:108:36)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
```

**Comment by Thomas-Smyth** [comment] 2020-12-08 20:30
The RCON client has been rewritten for SquadJS v2 so I will close this on the basis the issue is most likely no longer present or this existing research will not be relevant to any new issue.

**Closed as completed by Thomas-Smyth** 2020-12-08 20:30 UTC
Labels: core bug
