### ISSUE TITLE
discord-rcon has incorrect response for a given command

### ISSUE THREAD

**Issue by SeanWalsh95** [Team-Silver-Sphere/SquadJS#91] opened 2020-10-06 15:39 UTC
### Description of Issue
Using a command in discord-rcon like `adminbroadcast test` will often receive a response from the automated system for listing players

It appears to me that SquadJS does not make use of the [ability to set unique ID's for the RCON packets](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Packet_ID) so that matching requests to responses would be a simple task.

It seems SquadJS is only making use of two possible ID's `ID_MID` and `ID_END` a possible solution could be to either make more statically defined ID's specific to SquadJS for each possible request/response, or to generate a unique 32-bit little endian integer for each request and match that ID with responses from the server.

### Errors or Screenshots of Issue
Command:
`adminbroadcast test`

Response:
```
----- Active Players -----
ID: 107 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 4
ID: 52 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 7
ID: 38 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 5
ID: 76 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 4
ID: 94 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 7
ID: 62 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 6
ID: 64 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 7
ID: 57 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 4
ID: 90 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 5
ID: 102 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 1
ID: 59 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 7
ID: 53 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 3
ID: 21 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 3
ID: 11 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 6
ID: 20 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 9
ID: 67 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 3
ID: 3 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 8
ID: 75 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 5
ID: 13 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 2
ID: 73 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 5
ID: 32 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 6
ID: 113 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 1 | Squad ID: 6
ID: 17 | SteamID: 99999999999999999 | Name: REDACTED | Team ID: 2 | Squad ID: 3
```

### Squad Information
 * Plugins in Use: 
    discord-rcon
 * SquadJS Version:
    v1.4.8
 * Squad Version:
    v1.1

### System Information
 * Operating System:
    Ubuntu 20.04
 * NodeJS Version:
    v12.18.4
 * Yarn Version:
    v1.22.5

**Comment by Thomas-Smyth** [comment] 2020-12-08 20:33
The RCON client has been rewritten for SquadJS v2 so I will close this on the basis the issue is most likely no longer present or this existing research will not be relevant to any new issue.

**Closed as completed by Thomas-Smyth** 2020-12-08 20:33 UTC
Labels: core bug
